apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: icc
  namespace: {{ .Values.gateway.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  hostnames:
    - "icc.plt"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: icc
          port: 80
